name: Playwright Tests (Java)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Playwright CLI
        run: |
          wget https://github.com/microsoft/playwright-java/releases/latest/download/playwright-cli.zip
          unzip playwright-cli.zip -d ~/.playwright
          export PATH="$PATH:$HOME/.playwright"
          ~/.playwright/playwright install

      - name: Run Tests
        run: mvn clean test
